name: build
on:
  workflow_dispatch:
  push:
jobs:
  buiild-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Install Protobuf
        run: sudo snap install protobuf --classic

      - name: Generate sources from proto files
        run: make proto

      - name: Build this project
        run: go build ./cmd/...

      - name: Test this project
        run: go test ./pkg/...
