name: build
on:
  workflow_dispatch:
  push:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Install Protobuf
        run: sudo snap install protobuf --classic

      - name: Generate sources
        run: go generate ./pkg/...

      - name: Build targets
        run: go build ./cmd/...

      - name: Run tests
        run: go test -covermode atomic -coverprofile=profile.cov ./pkg/...

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Generate summary of test results
        run: ~/go/bin/gotestsum --junitfile build/test.xml

      - name: Download Testspace client
        run: curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C build

      - name: Configure Testspace client
        working-directory: build
        run: |
          ./testspace config url ${{ secrets.TESTSPACE_URL }}
          ./testspace config project ${{ secrets.TESTSPACE_PROJECT }}
          ./testspace config space ${{ github.ref_name }}

      - name: Send summary of test results to Testspace
        working-directory: build
        run: ./testspace [Tests]"test.xml"

      - name: Send code coverage info to Coveralls
        uses: shogo82148/actions-goveralls@v1.6.0
        with:
          path-to-profile: profile.cov
